EXEC += scaling

include ../Makefile.inc

# Extra dependencies for executables
# TODO: Automatically detect a .kern file in the dependencies?

# List the Kernel dependency (.kern) for each executable
scaling:  $(KERNEL_DIR)/Laplace.o
